apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks
  labels:
    app: eks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks
  template:
    metadata:
      labels:
        app: eks
    spec:
      containers:
      - name: eks
        image: my-nodejs-image:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: eks
spec:
  selector:
    app: eks
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
